version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=user
      - MYSQL_DATABASE=my_app_db
      - MYSQL_USER=user
    volumes:
      - mysql-data:/var/lib/mysql

  spring-app:
#    image:
    depends_on:
      - mysql
    ports:
      - 8080:8080

volumes:
  mysql-data:
